#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $CYBORG_REPO == "cyborg" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RlYW1Ycm5hdi9DeWJvcmcvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $CYBORG_REPO == "CYBORG" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RlYW1Ycm5hdi9DeWJvcmcvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $CYBORG_REPO =~ $regex ]]
    then
        if [[ $CYBORG_REPO_BRANCH ]]
        then
            echo "${CYBORG_REPO}/archive/${CYBORG_REPO_BRANCH}.zip"
        else
            echo "${CYBORG_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RlYW1Ycm5hdi9DeWJvcmcvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    fi
}


_starter () {
    local zippath
    zippath="mycyborg.zip"
    echo "••• DOWNLOADING CYBORG •••"
    wget -q $(_get_repolink) -O "$zippath"
    CYBORG_PATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    rm -rf "$zippath"
    sleep 5
    cd $CYBORG_PATH
    echo "••• STARTING CYBORG •••"

    python3 ./setup/updater.py ./requirements.txt requirements.txt
    python3 -m cyborg
}

_starter
